name: downloader
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  download:
    runs-on: ubuntu-latest
    steps:

    - name: Download
      run: |
        wget -O twrp.img "https://downloads.sourceforge.net/project/rmx3366-custom-roms/TWRP/TWRP_OPPO_realme_SM8250_AC.img"

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        tag_name: v1.2
        release_name: Release 1.2
        draft: false
        prerelease: false
        files: |
          ./twrp.img
